environment:
  type: "EndlessTmaze"
  reset_params:
    corridor_length: 5
    num_corridors: 3
    penalty: -0.01
    goal_reward: 1.0
    seed: null # Или укажите конкретное число, например, 42
    hints_override: null # Раскомментируйте и измените, если нужно переопределить подсказки
gamma: 0.995
lamda: 0.95
updates: 100
epochs: 3
n_workers: 32
worker_steps: 512
n_mini_batch: 8
value_loss_coefficient: 0.5
hidden_layer_size: 512
max_grad_norm: 0.25
transformer:
  num_blocks: 2
  embed_dim: 256
  num_heads: 4
  memory_length: 96
  positional_encoding: ""
  layer_norm: "pre"
  gtrxl: True
  gtrxl_bias: 0.2
learning_rate_schedule:
  initial: 2.75e-4
  final: 1.0e-5
  power: 1.0
  max_decay_steps: 10000
beta_schedule:
  initial: 0.001
  final: 0.000001
  power: 1.0
  max_decay_steps: 10000
clip_range_schedule:
  initial: 0.1
  final: 0.1
  power: 1.0
  max_decay_steps: 10000