# ---------------------------------------------------
#        YAML-конфигурация для GTrXL PPO
# ---------------------------------------------------

# --- Общие параметры ---
run_id: "gtrl_3_cor_fixed_5"
n_runs: 3

# Общие параметры, используемые по умолчанию
defaults:
  gamma: 0.995
  lamda: 0.95
  updates: 50
  epochs: 3
  n_workers: 32
  worker_steps: 512
  n_mini_batch: 8
  value_loss_coefficient: 0.5
  max_grad_norm: 0.25

# Параметры модели Actor-Critic
model:
  hidden_layer_size: 512

# Параметры трансформера (GTrXL)
transformer:
  num_blocks: 2
  embed_dim: 512
  num_heads: 4
  memory_length: 96
  positional_encoding: "learned"       # Опции: "relative", "learned", ""
  layer_norm: "pre"             # Опции: "pre", "post"
  gtrxl: True
  gtrxl_bias: 0.2

# --- Планировщики затухания гиперпараметров ---
learning_rate_schedule:
  initial: 2.75e-4
  final: 1.0e-5
  power: 1.0
  max_decay_steps: 10000

beta_schedule:
  initial: 0.001
  final: 0.000001
  power: 1.0
  max_decay_steps: 10000

clip_range_schedule:
  initial: 0.1
  final: 0.1
  power: 1.0
  max_decay_steps: 10000

# ---------------------------------------------------
#   Раздельные конфигурации для обучения и валидации
# ---------------------------------------------------

# Конфигурация среды обучения
train_env:
  num_corridors: 3
  penalty: -0.01
  goal_reward: 1.0
  # Настройки для длины коридора
  lengths:
    mode: "fixed"   # "uniform" для случайной длины, "fixed" для фиксированной
    max: 5            # Максимальная длина, если uniform. Фиксированная, если fixed.
    min: 1            # Минимальная длина, если uniform (игнорируется, если fixed)

# Конфигурация валидации
validation:
  enabled: True         # Включить/выключить валидацию
  val_every: 10         # Запускать валидацию каждые 10 обновлений
  # Параметры для среды валидации
  n_eval_episodes: 100
  best_model_metric: "success_mean"
  env:
    num_corridors: 3
    penalty: -0.01
    goal_reward: 1.0
    # Настройки для длины коридора
    lengths:
      mode: "fixed"     # "uniform" или "fixed"
      max: 5            # Длина коридора будет всегда 5
